version: '3.1'

services:

  orchestrator:
    build:
      context: ./orchestrator/
    container_name: orchestrator
    ports:
      - 8080:8080

  services-monitor:
    build:
      context: ./service-supervision-app
    container_name: services-monitor
    ports:
      - 8090:80
      
  hotel-booking:
    build:
      context: ./bookingservice/
    container_name: hotel-booking
    environment:
      APP_STOCK: 1000
    ports:
      - 8091:8090      
      
  flight-booking:
    build:
      context: ./bookingservice/
    container_name: flight-booking
    environment:
      APP_STOCK: 200
    ports:
      - 8092:8090
  
  taxi-booking:
    build:
      context: ./bookingservice/
    container_name: taxi-booking
    environment:
      APP_STOCK: 80
    ports:
      - 8093:8090
      
  meetingroom-booking:
    build:
      context: ./bookingservice/
    container_name: meetingroom-booking
    environment:
      APP_STOCK: 60
    ports:
      - 8094:8090